//patients
export const LIST_PATIENTS_SUCCESS = 'LIST_PATIENTS_SUCCESS'
export const LIST_PATIENTS_FAILURE = 'LIST_PATIENTS_FAILURE'
export const SEND_INFO = 'SEND_INFO'
//pagination
export const CHANGE_PAGE = 'CHANGE_PAGE'
export const ENTER_TOTAL_ITEMS = 'ENTER_TOTAL_ITEMS'
//therapists
export const GET_THERAPISTS_SUCCESS = 'GET_THERAPISTS_SUCCESS'
export const GET_THERAPISTS_FAILURE = 'GET_THERAPISTS_FAILURE'
export const SEND_THERAPIST = 'SEND_THERAPIST'
export const MAKE_REFERRAL_SUCCESS = 'MAKE_REFERRAL_SUCCESS'
export const MAKE_REFERRAL_FAILURE = 'MAKE_REFERRAL_FAILURE'
export const GET_THERAPIES_SUCCESS = 'GET_THERAPIES_SUCCESS'
export const GET_THERAPIES_FAILURE = 'GET_THERAPIES_FAILURE'
//therapy
export const CREATE_THERAPY_SUCCESS = 'CREATE_THERAPY_SUCCESS'
export const CREATE_THERAPY_FAILURE = 'CREATE_THERAPY_FAILURE'
export const PUT_THERAPY_SUCCESS = 'PUT_THERAPY_SUCCESS'
export const PUT_THERAPY_FAILURE = 'PUT_THERAPY_FAILURE'
export const RETRIEVE_THERAPY_SUCCESS = 'RETRIEVE_THERAPY_SUCCESS'
export const RETRIEVE_THERAPY_FAILURE = 'RETRIEVE_THERAPY_FAILURE'
